# Generated by Django 5.2.18 on 2026-10-06 17:30

import camp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=120)),
                ('social_handle', models.CharField(blank=True, max_length=80)),
                ('about', models.TextField(blank=True)),
                ('guardian_name', models.CharField(blank=True, max_length=160)),
                ('guardian_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=16)),
                ('notification_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('notification_error', models.CharField(blank=True, max_length=500)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=128)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('photo_consent', models.BooleanField(default=False)),
                ('guardian_consent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=camp.models.application_photo_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='camp.application')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
