# Generated by Django 5.2.18 on 2026-10-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationphoto',
            name='photo_type',
            field=models.CharField(choices=[('headshot', 'Headshot'), ('full_length', 'Full-length'), ('shoulder_up', 'Shoulder-up'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
