# Generated by Django 5.2.18 on 2026-10-07 06:18

import uuid

from django.db import migrations, models


def backfill_application_tokens_and_statuses(apps, schema_editor):
    application_model = apps.get_model("camp", "Application")
    database = schema_editor.connection.alias
    for application in application_model.objects.using(database).filter(
        share_token__isnull=True
    ).iterator():
        application.share_token = uuid.uuid4()
        application.save(using=database, update_fields=["share_token"])
    application_model.objects.using(database).filter(status="closed").update(
        status="not_selected"
    )


def restore_closed_status(apps, schema_editor):
    application_model = apps.get_model("camp", "Application")
    application_model.objects.using(schema_editor.connection.alias).filter(
        status="not_selected"
    ).update(status="closed")


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_applicationphoto_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='areas_of_interest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='available_full_five_weeks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('flexible', 'Flexible')], max_length=16),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.RunPython(
            backfill_application_tokens_and_statuses,
            restore_closed_status,
        ),
        migrations.AlterField(
            model_name='application',
            name='share_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('contacted', 'Contacted'), ('accepted', 'Accepted'), ('not_selected', 'Not Selected')], db_index=True, default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='applicationphoto',
            name='photo_type',
            field=models.CharField(choices=[('headshot', 'Headshot'), ('full_length', 'Full-length'), ('shoulder_up', 'Shoulder-up'), ('additional', 'Additional'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
