# Generated by Django 5.2.18 on 2026-10-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_application_areas_of_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='notification_error',
        ),
        migrations.RemoveField(
            model_name='application',
            name='notification_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='whatsapp_message_id',
        ),
    ]
