# Generated by Django 5.2.18 on 2026-10-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_remove_application_notification_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.CharField(db_index=True, editable=False, max_length=24, unique=True),
        ),
    ]
