# Generated by Django 5.2.18 on 2026-10-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_alter_application_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='application',
            name='available_full_five_weeks',
            field=models.BooleanField(blank=True, null=True, verbose_name='Available for the full 6 weeks?'),
        ),
        migrations.AlterField(
            model_name='applicationphoto',
            name='photo_type',
            field=models.CharField(choices=[('headshot', 'Profile / selfie'), ('full_length', 'Full-length'), ('shoulder_up', 'Shoulder-up'), ('additional', 'Additional'), ('other', 'Other')], default='other', max_length=16),
        ),
    ]
