# Generated by Django 5.2.18 on 2026-10-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0006_application_tiktok_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_modelling_experience',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has modelling experience?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='preferred_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Available day'),
        ),
    ]
