# Generated by Django 5.2.18 on 2026-10-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_application_has_modelling_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age_category',
            field=models.CharField(blank=True, choices=[('kids', 'Kids (5–12)'), ('teens', 'Teens (13–18)'), ('seniors', 'Seniors (19–28)')], max_length=12),
        ),
    ]
