# Generated by Django 5.2.18 on 2026-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0008_application_age_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=8),
        ),
    ]
