# Generated by Django 5.2.18 on 2026-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0009_application_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='application',
            name='town',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
